version: '3.8'

services:
  postgres:
    image: postgres:alpine
    restart: always
    environment:
      POSTGRES_USER: docker
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: fundo
    ports:
      - 5432:5432
  redis:
    image: redis:7-alpine
    restart: always
    ports:
      - 6379:6379
