package seeds

import "fund-o/api-server/internal/entity"

var ProjectCategorySeed = []entity.ProjectCategory{
	{
		Name: "Art",
		SubCategories: []entity.ProjectSubCategory{
			{Name: "Ceramics"},
			{Name: "Conceptual Art"},
			{Name: "Digital Art"},
			{Name: "Illustration"},
			{Name: "Installations"},
			{Name: "Mixed Media"},
			{Name: "Painting"},
			{Name: "Performance Art"},
			{Name: "Public Art"},
			{Name: "Sculpture"},
			{Name: "Social Practice"},
			{Name: "Textiles"},
			{Name: "Video Art"},
		},
	},
	{
		Name: "Comics",
		SubCategories: []entity.ProjectSubCategory{
			{Name: "Anthologies"},
			{Name: "Comic Books"},
			{Name: "Events"},
			{Name: "Graphic Novels"},
			{Name: "Webcomics"},
		},
	},
	{
		Name: "Crafts",
		SubCategories: []entity.ProjectSubCategory{
			{Name: "Candles"},
			{Name: "Crochet"},
			{Name: "DIY"},
			{Name: "Embroidery"},
			{Name: "Glass"},
			{Name: "Knitting"},
			{Name: "Pottery"},
			{Name: "Printing"},
			{Name: "Quilts"},
			{Name: "Stationery"},
			{Name: "Taxidermy"},
			{Name: "Weaving"},
			{Name: "Woodworking"},
		},
	},
	{
		Name: "Dance",
		SubCategories: []entity.ProjectSubCategory{
			{Name: "Performances"},
			{Name: "Residencies"},
			{Name: "Spaces"},
			{Name: "Workshops"},
		},
	},
	{
		Name: "Design",
		SubCategories: []entity.ProjectSubCategory{
			{Name: "Architecture"},
			{Name: "Civic Design"},
			{Name: "Graphic Design"},
			{Name: "Interactive Design"},
			{Name: "Product Design"},
			{Name: "Toys"},
			{Name: "Typography"},
		},
	},
	{
		Name: "Fashion",
		SubCategories: []entity.ProjectSubCategory{
			{Name: "Accessories"},
			{Name: "Apparel"},
			{Name: "Childrenswear"},
			{Name: "Couture"},
			{Name: "Footwear"},
			{Name: "Jewelry"},
			{Name: "Pet Fashion"},
			{Name: "Ready-to-wear"},
		},
	},
	{
		Name: "Film & Video",
		SubCategories: []entity.ProjectSubCategory{
			{Name: "Action"},
			{Name: "Animation"},
			{Name: "Comedy"},
			{Name: "Documentary"},
			{Name: "Drama"},
			{Name: "Experimental"},
			{Name: "Family"},
			{Name: "Fantasy"},
			{Name: "Festivals"},
			{Name: "Horror"},
			{Name: "Movie Theaters"},
			{Name: "Music Videos"},
			{Name: "Narrative Film"},
			{Name: "Romance"},
			{Name: "Science Fiction"},
			{Name: "Shorts"},
			{Name: "Television"},
			{Name: "Thrillers"},
			{Name: "Webseries"},
		},
	},
	{
		Name: "Food",
		SubCategories: []entity.ProjectSubCategory{
			{Name: "Bacon"},
			{Name: "Community Gardens"},
			{Name: "Cookbooks"},
			{Name: "Drinks"},
			{Name: "Events"},
			{Name: "Farmer's Markets"},
			{Name: "Farms"},
			{Name: "Food Trucks"},
			{Name: "Restaurants"},
			{Name: "Small Batch"},
			{Name: "Spaces"},
			{Name: "Vegan"},
		},
	},
	{
		Name: "Games",
		SubCategories: []entity.ProjectSubCategory{
			{Name: "Gaming Hardware"},
			{Name: "Live Games"},
			{Name: "Mobile Games"},
			{Name: "Playing Cards"},
			{Name: "Puzzles"},
			{Name: "Tabletop Games"},
			{Name: "Video Games"},
		},
	},
	{
		Name: "Journalism",
		SubCategories: []entity.ProjectSubCategory{
			{Name: "Audio"},
			{Name: "Photo"},
			{Name: "Print"},
			{Name: "Video"},
			{Name: "Web"},
		},
	},
	{
		Name: "Music",
		SubCategories: []entity.ProjectSubCategory{
			{Name: "Blues"},
			{Name: "Chiptune"},
			{Name: "Classical Music"},
			{Name: "Comedy"},
			{Name: "Country & Folk"},
			{Name: "Electronic Music"},
			{Name: "Faith"},
			{Name: "Hip-Hop"},
			{Name: "Indie Rock"},
			{Name: "Jazz"},
			{Name: "Kids"},
			{Name: "Latin"},
			{Name: "Metal"},
			{Name: "Pop"},
			{Name: "Punk"},
			{Name: "R&B"},
			{Name: "Rock"},
			{Name: "World Music"},
		},
	},
	{
		Name: "Photography",
		SubCategories: []entity.ProjectSubCategory{
			{Name: "Animals"},
			{Name: "Fine Art"},
			{Name: "Nature"},
			{Name: "People"},
			{Name: "Photobooks"},
			{Name: "Places"},
		},
	},
	{
		Name: "Publishing",
		SubCategories: []entity.ProjectSubCategory{
			{Name: "Academic"},
			{Name: "Anthologies"},
			{Name: "Art Books"},
			{Name: "Calendars"},
			{Name: "Children's Books"},
			{Name: "Comedy"},
			{Name: "Fiction"},
			{Name: "Letterpress"},
			{Name: "Literary Journals"},
			{Name: "Nonfiction"},
			{Name: "Periodicals"},
			{Name: "Poetry"},
			{Name: "Radio & Podcasts"},
			{Name: "Translations"},
			{Name: "Young Adult"},
			{Name: "Zines"},
		},
	},
	{
		Name: "Technology",
		SubCategories: []entity.ProjectSubCategory{
			{Name: "3D Printing"},
			{Name: "Apps"},
			{Name: "Camera Equipment"},
			{Name: "DIY Electronics"},
			{Name: "Fabrication Tools"},
			{Name: "Flight"},
			{Name: "Gadgets"},
			{Name: "Hardware"},
			{Name: "Makerspaces"},
			{Name: "Robots"},
			{Name: "Software"},
			{Name: "Sound"},
			{Name: "Space Exploration"},
			{Name: "Wearables"},
			{Name: "Web"},
		},
	},
	{
		Name: "Theater",
		SubCategories: []entity.ProjectSubCategory{
			{Name: "Comedy"},
			{Name: "Experimental"},
			{Name: "Festivals"},
			{Name: "Immersive"},
			{Name: "Musical"},
			{Name: "Plays"},
			{Name: "Spaces"},
		},
	},
}
